delete from rounds
where image_url ilike '%picsum%'
   or image_url ilike '%placeholder%'
   or image_url ilike '%.jpg'
   or image_url ilike '%.svg'
   or location_name in (
     'Eiffel Tower Exposition Grounds',
     'Guadalajara',
     'Toronto',
     'Vancouver',
     'Montevideo',
     'La Paz',
     'Brasília',
     'Nairobi',
     'Algiers',
     'Accra'
   );

delete from rounds
where image_url in (
  '/rounds/Cairo_1920.png',
  '/rounds/Shangai_1930.png',
  '/rounds/BuenosAires_1910.png',
  '/rounds/Berlino_1989.png',
  '/rounds/Roma_1950.png',
  '/rounds/Kyoto_1895.png',
  '/rounds/Singapore_1959.png',
  '/rounds/Baghdad_1932.png',
  '/rounds/NewOrleans_1925.png',
  '/rounds/Havana_1958.png',
  '/rounds/Valparaiso_1888.png',
  '/rounds/Bogota_1948.png',
  '/rounds/Lima_1920.png',
  '/rounds/Lagos_1960.png',
  '/rounds/SalvadorBahia_2000.png',
  '/rounds/Kinshasa_1974.png',
  '/rounds/Zanzibar_1890.png',
  '/rounds/Johannesburg_1994.png',
  '/rounds/Prague_1968.png',
  '/rounds/Athens_1896.png'
);

insert into rounds (
  location_name,
  country,
  lat,
  lng,
  year,
  image_url,
  explanation,
  geo_clues,
  time_clues,
  validation_notes,
  status,
  source_type,
  difficulty,
  approved
) values
  ('Cairo', 'Egypt', 30.0444, 31.2357, 1920, '/rounds/Cairo_1920.png', 'Cairo in 1920 is represented as an early modern Nile capital, with arid light, Islamic urban details, and interwar street life.', ARRAY['Dry North African light and flat urban terrain near a major river valley', 'Islamic architectural details such as domes, minarets, mashrabiya screens, or arched arcades', 'Dense Middle Eastern street life with markets, carts, and low-rise masonry buildings']::text[], ARRAY['Early automobiles or horse-drawn transport can coexist with traditional street activity', 'Interwar clothing such as fezzes, galabiyas, suits, and long dresses', 'No modern high-rises, satellite dishes, contemporary road markings, or postwar vehicles']::text[], 'Do not show the name of the location anywhere in the image. Do not include visible text, captions, labels, map names, titles, or signage that explicitly reveals the city, country, or exact place. Avoid readable signage unless it is generic and non-revealing. The image must contain clues, but must not directly state the answer.', 'approved', 'manual', 3, true),
  ('Shanghai', 'China', 31.2304, 121.4737, 1930, '/rounds/Shangai_1930.png', 'Shanghai in 1930 is represented as a treaty-port metropolis with river commerce, Art Deco density, and Chinese street life.', ARRAY['Riverfront commerce or Bund-like waterfront massing', 'Chinese street-market details mixed with international commercial architecture', 'Flat delta-city setting with trams, rickshaws, bicycles, or busy port streets']::text[], ARRAY['Interwar Art Deco, 1920s-1930s suits, and qipao silhouettes', 'Rickshaws, trams, bicycles, and early cars fit the period', 'Avoid communist-era iconography, post-1980 skyscrapers, and contemporary traffic infrastructure']::text[], 'Do not show the name of the location anywhere in the image. Do not include visible text, captions, labels, map names, titles, or signage that explicitly reveals the city, country, or exact place. Avoid readable signage unless it is generic and non-revealing. The image must contain clues, but must not directly state the answer.', 'approved', 'manual', 3, true),
  ('Buenos Aires', 'Argentina', -34.6037, -58.3816, 1910, '/rounds/BuenosAires_1910.png', 'Buenos Aires in 1910 is represented as a prosperous South American capital around the centennial era, with European-influenced avenues and period transport.', ARRAY['Broad avenues and ornate European-influenced civic architecture', 'Flat port-city layout with plazas, tram tracks, or formal boulevards', 'Southern Cone urban vegetation and street scale rather than tropical or Andean terrain']::text[], ARRAY['Edwardian-era dress, horse trams, electric trams, and early automobiles', 'Centennial-era civic grandeur before World War I', 'Avoid postwar buses, modern glass towers, and contemporary signage']::text[], 'Do not show the name of the location anywhere in the image. Do not include visible text, captions, labels, map names, titles, or signage that explicitly reveals the city, country, or exact place. Avoid readable signage unless it is generic and non-revealing. The image must contain clues, but must not directly state the answer.', 'approved', 'manual', 2, true),
  ('Berlin', 'Germany', 52.5200, 13.4050, 1989, '/rounds/Berlino_1989.png', 'Berlin in 1989 is represented as a divided late-Cold-War European capital with concrete barriers, central streets, crowds, and late-1980s material culture.', ARRAY['Central European stone architecture and broad flat avenues', 'Concrete wall sections, border infrastructure, or divided-city visual language', 'Temperate northern European urban density rather than desert or tropical clues']::text[], ARRAY['Late-1980s clothing, compact cars, cameras, and graffiti styles', 'Cold War border details hint at the final year of division', 'Avoid post-reunification street furniture, smartphones, LED displays, and contemporary construction']::text[], 'Do not show the name of the location anywhere in the image. Do not include visible text, captions, labels, map names, titles, or signage that explicitly reveals the city, country, or exact place. Avoid readable signage unless it is generic and non-revealing. The image must contain clues, but must not directly state the answer.', 'approved', 'manual', 2, true),
  ('Rome', 'Italy', 41.9028, 12.4964, 1950, '/rounds/Roma_1950.png', 'Rome in 1950 is represented through historic stone streets, classical and baroque urban fabric, and early postwar Italian daily life.', ARRAY['Mediterranean stone buildings, churches, ruins, piazzas, or narrow historic streets', 'Scooters, cafes, and compact urban street life fitting central Italy', 'Warm light and architectural layers from antiquity through the early modern period']::text[], ARRAY['Postwar clothing, early Vespas, trams, and 1940s-1950s cars', 'A scene after World War II but before mass tourism and modern traffic', 'Avoid digital signs, contemporary storefronts, modern road signs, and recent vehicles']::text[], 'Do not show the name of the location anywhere in the image. Do not include visible text, captions, labels, map names, titles, or signage that explicitly reveals the city, country, or exact place. Avoid readable signage unless it is generic and non-revealing. The image must contain clues, but must not directly state the answer.', 'approved', 'manual', 2, true),
  ('Kyoto', 'Japan', 35.0116, 135.7681, 1895, '/rounds/Kyoto_1895.png', 'Kyoto in 1895 is represented as a former imperial Japanese city in the Meiji period, with temples, wooden streets, and transitional dress.', ARRAY['Wooden machiya townhouses, temple roofs, gardens, or narrow lanes', 'Mountain-rimmed basin atmosphere and traditional Japanese urban fabric', 'Shrines, tiled roofs, stone lanterns, or small bridges']::text[], ARRAY['Meiji-era mix of kimono, early Western dress, rickshaws, and pre-automobile streets', 'Late 19th-century visual cues rather than Edo or postwar Japan', 'Avoid neon, bullet trains, modern overhead utilities, and postwar commercial signage']::text[], 'Do not show the name of the location anywhere in the image. Do not include visible text, captions, labels, map names, titles, or signage that explicitly reveals the city, country, or exact place. Avoid readable signage unless it is generic and non-revealing. The image must contain clues, but must not directly state the answer.', 'approved', 'manual', 3, true),
  ('Singapore', 'Singapore', 1.3521, 103.8198, 1959, '/rounds/Singapore_1959.png', 'Singapore in 1959 is represented as a tropical port city at the start of self-government, with shophouses, harbor activity, and multicultural street life.', ARRAY['Tropical humidity, colonial-era shophouses, port commerce, and dense markets', 'Malay, Chinese, Indian, and British-influenced urban details', 'Flat island-city setting with waterfront or commercial street clues']::text[], ARRAY['1950s buses, bicycles, clothing, and shopfront design', 'Self-government period before full independence', 'Avoid Marina Bay skyline, container terminals, MRT infrastructure, and contemporary towers']::text[], 'Do not show the name of the location anywhere in the image. Do not include visible text, captions, labels, map names, titles, or signage that explicitly reveals the city, country, or exact place. Avoid readable signage unless it is generic and non-revealing. The image must contain clues, but must not directly state the answer.', 'approved', 'manual', 3, true),
  ('Baghdad', 'Iraq', 33.3152, 44.3661, 1932, '/rounds/Baghdad_1932.png', 'Baghdad in 1932 is represented as a Mesopotamian river city at the start of the Kingdom of Iraq era, with arid architecture and interwar transport.', ARRAY['Arid river-city environment with palm trees, bazaars, and courtyard architecture', 'Tigris-side clues such as bridges, boats, or low riverbank development', 'Middle Eastern street life and Islamic architectural details']::text[], ARRAY['Interwar clothing and early cars fit the kingdom-era setting', 'Pre-World War II atmosphere without Ottoman-era dominance', 'Avoid Baathist monuments, modern highways, and contemporary concrete skyline']::text[], 'Do not show the name of the location anywhere in the image. Do not include visible text, captions, labels, map names, titles, or signage that explicitly reveals the city, country, or exact place. Avoid readable signage unless it is generic and non-revealing. The image must contain clues, but must not directly state the answer.', 'approved', 'manual', 4, true),
  ('New Orleans', 'United States', 29.9511, -90.0715, 1925, '/rounds/NewOrleans_1925.png', 'New Orleans in 1925 is represented as a Gulf Coast jazz-era port city with balconies, humid streets, streetcars, and period nightlife cues.', ARRAY['Cast-iron balconies, French or Spanish colonial streetscapes, and humid subtropical vegetation', 'Streetcar tracks, river-port atmosphere, and low-rise historic neighborhoods', 'Gulf Coast architecture distinct from northern United States cities']::text[], ARRAY['Jazz Age clothing, 1920s automobiles, streetcars, and analog storefronts', 'Prohibition-era mood without explicit written labels', 'Avoid postwar neon strips, modern tourist branding, and contemporary vehicles']::text[], 'Do not show the name of the location anywhere in the image. Do not include visible text, captions, labels, map names, titles, or signage that explicitly reveals the city, country, or exact place. Avoid readable signage unless it is generic and non-revealing. The image must contain clues, but must not directly state the answer.', 'approved', 'manual', 2, true),
  ('Havana', 'Cuba', 23.1136, -82.3666, 1958, '/rounds/Havana_1958.png', 'Havana in 1958 is represented as a Caribbean capital just before the revolution, with tropical streets, mid-century cars, and colonial facades.', ARRAY['Caribbean light, arcaded colonial buildings, palm-lined streets, and waterfront texture', 'Spanish colonial and Art Deco architectural mix in a tropical island setting', 'Plazas, balconies, and coastal humidity']::text[], ARRAY['1950s American cars, pre-revolution nightlife styling, and mid-century clothing', 'Late Batista-era atmosphere before 1959 revolutionary iconography', 'Avoid modern resorts, recent vehicles, and post-revolution political murals']::text[], 'Do not show the name of the location anywhere in the image. Do not include visible text, captions, labels, map names, titles, or signage that explicitly reveals the city, country, or exact place. Avoid readable signage unless it is generic and non-revealing. The image must contain clues, but must not directly state the answer.', 'approved', 'manual', 3, true),
  ('Valparaíso', 'Chile', -33.0472, -71.6127, 1888, '/rounds/Valparaiso_1888.png', 'Valparaíso in 1888 is represented as a steep Pacific port with hills, maritime commerce, and late-19th-century urban texture.', ARRAY['Steep hills descending to a harbor and dense hillside housing', 'Pacific port infrastructure with ships, warehouses, docks, or stairways', 'South American coastal terrain rather than inland plains']::text[], ARRAY['Late-19th-century clothing, sailing or steam vessels, and horse-era streets', 'Pre-automobile urban life before modern port equipment', 'Avoid container cranes, modern roads, and contemporary hillside towers']::text[], 'Do not show the name of the location anywhere in the image. Do not include visible text, captions, labels, map names, titles, or signage that explicitly reveals the city, country, or exact place. Avoid readable signage unless it is generic and non-revealing. The image must contain clues, but must not directly state the answer.', 'approved', 'manual', 4, true),
  ('Bogotá', 'Colombia', 4.7110, -74.0721, 1948, '/rounds/Bogota_1948.png', 'Bogotá in 1948 is represented as an Andean capital during a turbulent mid-century moment, with altitude, colonial streets, civic squares, and period crowds.', ARRAY['High-altitude Andean light, mountain backdrop, colonial or republican facades, and plazas', 'Cool-climate clothing and dense streets distinct from Caribbean Colombia', 'Streetcars, stone churches, or civic buildings']::text[], ARRAY['1940s clothing, older trams, unrest-damaged streets, or period vehicles', 'Mid-century street-reporting atmosphere before modern transit systems', 'Avoid modern TransMilenio buses, glass office towers, and contemporary signage']::text[], 'Do not show the name of the location anywhere in the image. Do not include visible text, captions, labels, map names, titles, or signage that explicitly reveals the city, country, or exact place. Avoid readable signage unless it is generic and non-revealing. The image must contain clues, but must not directly state the answer.', 'approved', 'manual', 4, true),
  ('Lima', 'Peru', -12.0464, -77.0428, 1920, '/rounds/Lima_1920.png', 'Lima in 1920 is represented as a Pacific coastal capital with colonial balconies, arid light, plazas, and early-20th-century urban life.', ARRAY['Dry coastal atmosphere, colonial wooden balconies, plazas, and low-rise civic architecture', 'Pacific South American capital setting without rainforest or high mountain streets', 'Churches, arcades, tramlines, or historic center streets']::text[], ARRAY['Early-20th-century clothing, trams, horse carts, and few early cars', 'Republican-era city life rather than colonial or late-modern scenes', 'Avoid concrete expressways, contemporary buses, and glass high-rises']::text[], 'Do not show the name of the location anywhere in the image. Do not include visible text, captions, labels, map names, titles, or signage that explicitly reveals the city, country, or exact place. Avoid readable signage unless it is generic and non-revealing. The image must contain clues, but must not directly state the answer.', 'approved', 'manual', 3, true),
  ('Lagos', 'Nigeria', 6.5244, 3.3792, 1960, '/rounds/Lagos_1960.png', 'Lagos in 1960 is represented as a humid West African coastal capital at independence, with harbor activity, tropical streets, and early postcolonial details.', ARRAY['Tropical coastal vegetation, lagoon or harbor setting, and dense West African street activity', 'Colonial-era public buildings, markets, and low-rise commercial streets', 'Warm humid atmosphere and waterfront cues']::text[], ARRAY['1960 independence-era clothing, buses, flags, or civic ceremony cues', 'Transition from colonial rule to independence', 'Avoid modern megacity flyovers, contemporary towers, and post-1970s vehicles']::text[], 'Do not show the name of the location anywhere in the image. Do not include visible text, captions, labels, map names, titles, or signage that explicitly reveals the city, country, or exact place. Avoid readable signage unless it is generic and non-revealing. The image must contain clues, but must not directly state the answer.', 'approved', 'manual', 4, true),
  ('Salvador', 'Brazil', -12.9777, -38.5016, 2000, '/rounds/SalvadorBahia_2000.png', 'Salvador in 2000 is represented as an Afro-Brazilian coastal city with colonial hills, tropical color, and late-20th-century urban details.', ARRAY['Steep colonial streets, brightly painted facades, tropical Atlantic light, and bay or coastal hints', 'Portuguese baroque churches, cobblestone plazas, or hillside urban form', 'Afro-Brazilian cultural atmosphere through clothing, music, or street life without explicit text']::text[], ARRAY['Late-1990s to year-2000 cars, clothing, and street materials', 'Contemporary enough for 2000 but not current-day', 'Avoid smartphones, recent LED signage, and new infrastructure from the 2010s or later']::text[], 'Do not show the name of the location anywhere in the image. Do not include visible text, captions, labels, map names, titles, or signage that explicitly reveals the city, country, or exact place. Avoid readable signage unless it is generic and non-revealing. The image must contain clues, but must not directly state the answer.', 'approved', 'manual', 3, true),
  ('Kinshasa', 'Zaire', -4.4419, 15.2663, 1974, '/rounds/Kinshasa_1974.png', 'Kinshasa in 1974 is represented in the Zaire era, with tropical urban life, river proximity, and 1970s styling.', ARRAY['Equatorial urban vegetation, Congo River proximity, and broad central African streets', 'Postcolonial civic buildings, markets, and low-rise tropical city texture', 'Humid central African capital atmosphere rather than desert or Mediterranean cues']::text[], ARRAY['1970s clothing, cars, music posters, or boxing-event atmosphere', 'Zaire-era context rather than present-day Democratic Republic of Congo symbols', 'Avoid smartphones, modern billboards, and recent high-rise developments']::text[], 'Do not show the name of the location anywhere in the image. Do not include visible text, captions, labels, map names, titles, or signage that explicitly reveals the city, country, or exact place. Avoid readable signage unless it is generic and non-revealing. The image must contain clues, but must not directly state the answer.', 'approved', 'manual', 4, true),
  ('Zanzibar City', 'Tanzania', -6.1659, 39.2026, 1890, '/rounds/Zanzibar_1890.png', 'Zanzibar City in 1890 is represented as an Indian Ocean Swahili port with coral-stone architecture, dhows, and late-19th-century trading networks.', ARRAY['Coral-stone buildings, carved wooden doors, narrow lanes, and Indian Ocean waterfront', 'Dhows, spice-trade context, and Swahili-Arab architectural details', 'Tropical island light and port activity']::text[], ARRAY['Late-19th-century dress, sailing vessels, and protectorate-era material culture', 'Pre-automobile maritime atmosphere', 'Avoid modern ferries, concrete hotels, electricity-heavy streets, and contemporary signage']::text[], 'Do not show the name of the location anywhere in the image. Do not include visible text, captions, labels, map names, titles, or signage that explicitly reveals the city, country, or exact place. Avoid readable signage unless it is generic and non-revealing. The image must contain clues, but must not directly state the answer.', 'approved', 'manual', 4, true),
  ('Johannesburg', 'South Africa', -26.2041, 28.0473, 1994, '/rounds/Johannesburg_1994.png', 'Johannesburg in 1994 is represented as a highveld city at South Africa''s democratic transition, with inland urban form, crowds, and late-20th-century details.', ARRAY['Highveld light, mining-era urban fabric, broad streets, and inland South African city scale', 'Civic queues, townships, or downtown architecture', 'Dry plateau setting rather than coastal Table Mountain or tropical vegetation']::text[], ARRAY['1990s clothing, election queues, press cameras, and period cars', 'Democratic-transition era atmosphere without direct labels', 'Avoid smartphones, contemporary mall architecture, and post-2010 urban upgrades']::text[], 'Do not show the name of the location anywhere in the image. Do not include visible text, captions, labels, map names, titles, or signage that explicitly reveals the city, country, or exact place. Avoid readable signage unless it is generic and non-revealing. The image must contain clues, but must not directly state the answer.', 'approved', 'manual', 3, true),
  ('Prague', 'Czech lands', 50.0755, 14.4378, 1968, '/rounds/Prague_1968.png', 'Prague in 1968 is represented as a Central European historic city during the Prague Spring and invasion year, with period vehicles and architecture.', ARRAY['Gothic, baroque, or Art Nouveau urban fabric, cobblestones, and tram streets', 'Central European river-city or square setting with dense historic buildings', 'Temperate masonry streets distinct from western modernist capitals']::text[], ARRAY['1960s clothing, Warsaw Pact tanks or military vehicles, trams, and analog cameras', 'Late socialist Czechoslovakia atmosphere rather than modern Czech Republic', 'Avoid post-communist storefronts, contemporary cars, and modern tourist signage']::text[], 'Do not show the name of the location anywhere in the image. Do not include visible text, captions, labels, map names, titles, or signage that explicitly reveals the city, country, or exact place. Avoid readable signage unless it is generic and non-revealing. The image must contain clues, but must not directly state the answer.', 'approved', 'manual', 3, true),
  ('Athens', 'Greece', 37.9838, 23.7275, 1896, '/rounds/Athens_1896.png', 'Athens in 1896 is represented as a Mediterranean capital around the first modern Olympics, with neoclassical buildings, ancient ruins, and late-19th-century crowds.', ARRAY['Neoclassical civic buildings, marble ruins, dry Mediterranean hills, and ancient-stone context', 'Compact historic streets and open archaeological or civic spaces', 'Greek light, terrain, and architecture rather than northern European cues']::text[], ARRAY['Late-19th-century clothing, horse-era transport, and early Olympic crowd cues', 'First-modern-Olympics era without naming the event or city', 'Avoid cars, modern stadium seating, overhead highways, and contemporary signage']::text[], 'Do not show the name of the location anywhere in the image. Do not include visible text, captions, labels, map names, titles, or signage that explicitly reveals the city, country, or exact place. Avoid readable signage unless it is generic and non-revealing. The image must contain clues, but must not directly state the answer.', 'approved', 'manual', 3, true);

select location_name, country, year, image_url, approved, status
from rounds
order by country, location_name;
